### ISSUE TITLE
Animate lights

### ISSUE THREAD

**Issue by Ricardo1980** [thkl/homebridge-philipshue#14]
Is it possible to create scenes with animated lights? (colors) Thanks.

**Comment by stephenyeargin** [comment]
As far as I know, that isn't a supported feature in HomeKit. There is support for the `colorloop` effect in the underlying node library, but I bet it would only work with custom programming.

Reference: https://github.com/peter-murray/node-hue-api/blob/master/hue-api/lightstate.js#L162-170

**Comment by thkl** [comment]
home kit only supports a few devices with a limited count of characteristics. eg a lightbulb with state (on/of)  and level (0-100%) . animations are currently not supported by homekit, so there is no way to set this up.
