### ISSUE TITLE
"excludephilips": true not working

### ISSUE THREAD

**Issue by JotWee** [thkl/homebridge-philipshue#7]
I change my config.json from
`"excludephilips": false`
to
`"excludephilips": true`
but I still see all the Philips lamps

**Comment by jjiburg** [comment]
Also have this problem as well. Would like to use native homekit integration from the hub for my philips bulbs while having homebridge interface with my 3rd party bulbs, but having all of my Philips bulbs listed twice is quite ugly. I guess the workaround is to just interface with homebridge, but as we all know you're playing with fire with that one.

**Comment by jjiburg** [comment]
I think I may have found a quick fix. It seems as though npm-install isn't getting the latest version of index.js. 

Copy and paste the contents of [the raw index.js file](https://raw.githubusercontent.com/thkl/homebridge-philipshue/master/index.js) into your local homebridge-philipshue installation and that should fix it. I don't have any third party bulbs connected at the moment, but it is now ignoring the philips bulbs and not publishing them to homekit.

**Comment by JotWee** [comment]
@jjiburg thank you very much 😊 works as expected now
